name = input("Enter Name: ")
empid = input("Enter EmpID: ")
gross_monthly = float(input("Enter Gross Monthly Salary: "))
annual_gross = float(input("Enter Annual Gross Salary: "))
taxable_income = float(input("Enter Taxable Income: "))
tax = float(input("Enter Tax Payable: "))
net_salary = float(input("Enter Annual Net Salary: "))

print("\nEMPLOYEE TAX REPORT")
print("----------------------")
print("Name:", name)
print("EmpID:", empid)
print("Gross Monthly Salary:", gross_monthly)
print("Annual Gross Salary:", annual_gross)
print("Taxable Income:", taxable_income)
print("Tax Payable:", tax)
print("Annual Net Salary:", net_salary)
